// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBVzGYCI8zlD51kvODh7u2sDWoZuMfY7g',
    appId: '1:603252764927:web:dde7b538bbfba07e3e5cca',
    messagingSenderId: '603252764927',
    projectId: 'maqsadfb',
    authDomain: 'maqsadfb.firebaseapp.com',
    storageBucket: 'maqsadfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5Ye7MBrCopThLL4HZVagRNyXw2-FGOU',
    appId: '1:603252764927:android:b31f4d1cf245d1ec3e5cca',
    messagingSenderId: '603252764927',
    projectId: 'maqsadfb',
    storageBucket: 'maqsadfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0D1p0MFeClOA-E4l_plkDk-bvg-uHA1I',
    appId: '1:603252764927:ios:45be7cb74f451eea3e5cca',
    messagingSenderId: '603252764927',
    projectId: 'maqsadfb',
    storageBucket: 'maqsadfb.firebasestorage.app',
    iosBundleId: 'com.example.maqsad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0D1p0MFeClOA-E4l_plkDk-bvg-uHA1I',
    appId: '1:603252764927:ios:45be7cb74f451eea3e5cca',
    messagingSenderId: '603252764927',
    projectId: 'maqsadfb',
    storageBucket: 'maqsadfb.firebasestorage.app',
    iosBundleId: 'com.example.maqsad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBVzGYCI8zlD51kvODh7u2sDWoZuMfY7g',
    appId: '1:603252764927:web:27dedc9ffbc564543e5cca',
    messagingSenderId: '603252764927',
    projectId: 'maqsadfb',
    authDomain: 'maqsadfb.firebaseapp.com',
    storageBucket: 'maqsadfb.firebasestorage.app',
  );
}
